apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  hdpdeploy.properties: |-
{{ tpl (.Files.Get (printf "config/%s" .Values.hdp.configurationFileName)) . | indent 4 }}
