apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- if .Values.haproxy.kubernetesIngress.enabled }}
    haproxy.org/affinity: "true"
    haproxy.org/cookie-persistence: HDP-SESSION
    haproxy.org/forwarded-for: "true"
    haproxy.org/load-balance: roundrobin
    haproxy.org/timeout-check: 5m
    haproxy.org/timeout-server: 5m
    {{- end}}
    kubernetes.io/ingress.class: {{ .Values.kubernetesingress.controller.ingressClass }}
  name: {{ .Release.Name }}-{{ .Values.haproxy.kubernetesIngress.ingressName }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.kubernetesingress.controller.ingressClass }}
  rules:
  - host: {{ .Values.hdp.loadbalancer.hostName }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-{{ .Values.hdp.services.hdpService.name }}
            port:
              number: {{ .Values.hdp.ports.hdpServer.port }}
        path: /
        pathType: Prefix
      - backend:
          service:
            name: {{ .Release.Name }}-{{ .Values.hdp.services.notificationService.name }}
            port:
              number: {{ .Values.hdp.ports.notificationServer.port }}
        path: {{ .Values.hdp.services.notificationService.aclPath }}
        pathType: Prefix
      - backend:
          service:
            name: {{ .Release.Name }}-{{ .Values.hdp.services.opAccessorService.name }}
            port:
              number: {{ .Values.hdp.ports.opAccessor.port }}
        path: {{ .Values.hdp.services.opAccessorService.aclPath }}_{{ .Release.Name }}-{{ .Values.hdp.services.hdpService.name }}_{{ .Values.hdp.ports.opAccessor.port }}
        pathType: Prefix
  {{- if .Values.haproxy.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.hdp.loadbalancer.hostName }}
    secretName: tls-cert
  {{- end -}}
