apiVersion: v1
kind: Service
metadata:
  {{- if .Values.haproxy.kubernetesIngress.enabled }}
  annotations:
    haproxy.org/check: "{{ .Values.hdp.services.hdpService.check }}"
    haproxy.org/check-http: HEAD {{ .Values.hdp.services.hdpService.checkPath }}
    haproxy.org/check-interval: {{ .Values.hdp.services.hdpService.checkInterval }}
  {{- end}}  
  name: {{ .Release.Name }}-{{ .Values.hdp.services.hdpService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.haproxy.kubernetesIngress.enabled }}
  type: ClusterIP
  {{ else }}
  type: NodePort
  {{- end}}
  ports:
  - name: hdpserver-port
    port: {{.Values.hdp.ports.hdpServer.port}}
    protocol: TCP
    targetPort: {{.Values.hdp.ports.hdpServer.targetPort}}
  - name: internal-api-port
    port: 8190
    protocol: TCP
    targetPort: 8190
  selector:
    app: hdp-server-app
