apiVersion: v1
kind: Service
metadata:
  {{- if .Values.haproxy.kubernetesIngress.enabled }}
  annotations:
    haproxy.org/check: "{{ .Values.hdp.services.opAccessorService.check }}"
    haproxy.org/check-http: HEAD {{ .Values.hdp.services.opAccessorService.checkPath }}
    haproxy.org/check-interval: {{ .Values.hdp.services.opAccessorService.checkInterval }}
    haproxy.org/route-acl: path_end -i {{ .Values.hdp.services.opAccessorService.aclPath }}_{{ .Release.Name }}-{{ .Values.hdp.services.hdpService.name }}_{{ .Values.hdp.ports.opAccessor.port }}
  {{- end }}    
  name: {{ .Release.Name }}-{{ .Values.hdp.services.opAccessorService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.haproxy.kubernetesIngress.enabled }}
  type: ClusterIP
  {{ else }}
  type: NodePort
  {{- end}}
  ports:
  - name: opaccessor-port
    port: {{ .Values.hdp.ports.opAccessor.port }}
    protocol: TCP
    targetPort: {{ .Values.hdp.ports.opAccessor.targetPort }}
  selector:
    app: hdp-server-app
