apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-shared-storage-volume
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.hdp.persistence.size}}
  storageClassName: {{.Values.hdp.persistence.storageClassName}}
