hdp:
  image:
    repository: dcihdp.azurecr.io/hdp-docker-4.6.1:2057
  ports:
    http:
      containerPort: 8080
      nodePort: 30080
    https:
      containerPort: 8443
      nodePort: 30443  
  deploy:
    properties:
      HDP_DATABASE_HOSTNAME: hdp-lb-server-deploy-postgresql.default.svc.cluster.local
      HDP_DATABASE_PORT: 5432
      HDP_DATABASE_NAME: hdp
      HDP_DATABASE_VENDOR: postgresql
    mountPath: /hdpshare
  resources:
    storage:
      size: 1Gi
postgres:
  enabled: true
  init:
    postgres_user: postgres
    dbname: postgres
  hdp:
    schemaname: hdp
    dbname: hdp
postgresql:
  global:
    postgresql:
      auth:
        existingSecret: "postgres-secrets"
        secretKeys:
          adminPasswordKey: "postgres.db.password"
  primary:
    initdb:
      scriptsConfigMap: "postgres-initsql"
    persistence:
      size: 1Gi