apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdp-common-pvc
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.hdp.resources.storage.size}}
  storageClassName: azurefile-csi