apiVersion: v1
kind: Service
metadata:
  name: hdp-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    hdp: test
  ports:
  - name: http
    port: {{.Values.hdp.ports.http.containerPort}}
    targetPort: {{.Values.hdp.ports.http.containerPort}}
    nodePort: {{.Values.hdp.ports.http.nodePort}}
  - name: https
    port: {{.Values.hdp.ports.https.containerPort}}
    targetPort: {{.Values.hdp.ports.https.containerPort}}
    nodePort: {{.Values.hdp.ports.https.nodePort}}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 86400